Adding support for APL render document and user event
taimos/ask-sdk-test pull request #15
Opened 2020-05-27 07:36 UTC by brightsparc

* **Please check if the PR fulfills these requirements**

- [x] The commit message describes your change
- [x] Tests for the changes have been added if possible (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Changes are mentioned in the changelog (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add support for APL render document validation, and UserEvent touch events.

* **What is the current behavior?** (You can also link to an open issue here)
This is a new features.

* **What is the new behavior (if this is a feature change)?**
Ability to support APL templates and user events.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their setup due to this PR?)
No breaking changes.

* **Other information**:

2020-06-01 18:13 UTC, hoegertn requested changes
Thanks. This looks great. Please fix the two minor typos. I will merge it then.

2020-06-01 18:13 UTC, hoegertn commented on lib/tester/AplValidator.ts
> +                fail('the response did not play a stream');
Wrong error message

2020-06-01 18:13 UTC, hoegertn commented on CHANGELOG.md
> +* feat: add `renderDocument` parameter used to asset templates in `AplValidator` class.
assert

2020-06-02 06:10 UTC, hoegertn approved these changes

2020-06-02 06:10 UTC, merged

2020-06-29 06:26 UTC, brightsparc commented
Hi @hoegertn are you able to push this latest update to NPM repo?

Also I notice the docs are slight out of date if you wanted to do `npm run build` as part of that push.

2020-07-01 20:51 UTC, hoegertn commented
Release as 2.5.0

The `npm run build` is done automatically on release.

Thanks for reminding me.